### PR TITLE
Add tailwindcss and update packages

### PR DESCRIPTION
**Pull request by Tes3awy**
**Breaking changes**
 
1- Add [tailwindcss](https://tailwindcss.com/) as the CSS framework.
2- Add `tailwind.config.js` file and updated `postcss.config.js`. 
3- Add tailwind preflight to _tailwind.css and link within styles.css,
4- Update packages considering they are working perfectly.
5- Update the `.gitignore` file and deleted lock files.
6- Extract scss/sass into a separate test.

### CODE REVIEW

**Comment by EvanAgee** [comment]
Very nice work @Tes3awy! Definitely super useful but I'm not entirely sure that I want to commit to any specific CSS framework for this project since the idea is for it to be as un-opinionated as possible. Let me think about it for a bit and figure out a good way to make this available to others without it being in master. I'll definitely make use of it myself though, thanks!

**Comment by Tes3awy** [comment]
Sure @EvanAgee. I just want to explain my point of view in adding `tailwindcss` to the projects. Tailwind is a utility-first CSS framework. It's not like bootstrap or vuetify. It doesn't use components or directives. It's just pure CSS classes. Also, it includes its media queries and that staff you already defined in the `styles.css` file. I'd like you to have a look at this [page](https://tailwindcss.com/#what-is-tailwind). The title is **Most CSS frameworks do too much**. So it's probably unopinionated and should be okay with the project. Thank you @EvanAgee for this amazing work :)

**Comment by EvanAgee** [comment]
@Tes3awy Oh I'm a big fan of Tailwind, no doubt about it! I'm leaning more and more towards merging this since no one HAS to use it if they don't want to.

**Comment by EvanAgee** [comment]
@Tes3awy as part of this PR would you also update the README to include note(s) about the Tailwind integration?

**Comment by Tes3awy** [comment]
Of course. I am just waiting for the pull-request to get accepted and then after update the Readme file.

**Comment by Tes3awy** [comment]
Hello @EvanAgee, I updated the README.md file to include some references for the newly added features.

**Comment by EvanAgee** [comment]
Thanks for all of your work on this, I'm about to release an update that includes Tailwind!

**Pull request closed without merging**
